# Generated by Django 4.2.2 on 2023-07-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmaps", "0002_alter_roadmapcateg_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roadmap",
            old_name="Creator",
            new_name="creator",
        ),
    ]
